name: Mbed Build CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "**" ]
jobs:
  build:
    name: Compile Firmware
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      matrix:
        robot: [Infantry, Sentry, Hero, TestBench]
    
    container:
      image: ghcr.io/armmbed/mbed-os-env:master-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install CMake 3.29
        run: wget -qO- https://github.com/Kitware/CMake/releases/download/v3.29.0/cmake-3.29.0-linux-x86_64.tar.gz | tar --strip-components=1 -xz -C /usr/local

      - name: Deploy Mbed OS
        run: mbed-tools deploy

      - name: Configure Mbed
        run: mbed-tools configure -m NUCLEO_F446RE -t GCC_ARM

      - name: Build ${{ matrix.robot }}
        run: cmake -S . -B cmake-build-debug -GNinja -DCMAKE_BUILD_TYPE=Develop && cmake --build cmake-build-debug --target TR-${{ matrix.robot }} -j

      - name: Upload Binary
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.robot }}-firmware
          path: cmake-build-debug/**/*.bin
          if-no-files-found: error